# Form implementation generated from reading ui file '.\LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QButtonGroup


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1250, 809)
        Form.setMinimumSize(QtCore.QSize(1400, 500))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setText("")
        # self.label.setPixmap(QtGui.QPixmap("./resource/images/background.jpg"))
        self.label.setPixmap(QtGui.QPixmap(":/resource/images/gd3u3ibyyp.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.widget = QtWidgets.QWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(360, 0))
        self.widget.setMaximumSize(QtCore.QSize(360, 16777215))
        self.widget.setStyleSheet("QLabel{\n"
                                  "    font: 13px \'Microsoft YaHei\'\n"
                                  "}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setSpacing(9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 100))
        self.label_2.setMaximumSize(QtCore.QSize(100, 100))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/resource/images/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.setVisible(False)
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = LineEdit(parent=self.widget)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.label_3 = BodyLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.BodyLabel = BodyLabel(parent=self.widget)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout_2.addWidget(self.BodyLabel)
        self.PushButton = PushButton(parent=self.widget)
        self.PushButton.setObjectName("PushButton")
        self.verticalLayout_2.addWidget(self.PushButton)
        self.LineEdit = LineEdit(parent=self.widget)
        self.LineEdit.setObjectName("LineEdit")
        self.verticalLayout_2.addWidget(self.LineEdit)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.RadioButton_1 = RadioButton(parent=self.widget)
        self.RadioButton_1.setObjectName("cmcc_rbtn")
        self.horizontalLayout_3.addWidget(self.RadioButton_1)
        self.RadioButton_2 = RadioButton(parent=self.widget)
        self.RadioButton_2.setObjectName("unicom_rbtn")
        self.horizontalLayout_3.addWidget(self.RadioButton_2)
        self.RadioButton_3 = RadioButton(parent=self.widget)
        self.RadioButton_3.setObjectName("telecom_rbtn")
        self.horizontalLayout_3.addWidget(self.RadioButton_3)

        self.ispgroup = QButtonGroup(parent=self.widget)  # group
        self.ispgroup.addButton(self.RadioButton_1)
        self.ispgroup.addButton(self.RadioButton_2)
        self.ispgroup.addButton(self.RadioButton_3)

        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.label_5 = BodyLabel(parent=self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)

        self.lineEdit_3 = LineEdit(parent=self.widget)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.label_6 = BodyLabel(parent=self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.lineEdit_4 = LineEdit(parent=self.widget)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.RadioButton_5 = RadioButton(parent=self.widget)
        self.RadioButton_5.setObjectName("RadioButton_5")
        self.horizontalLayout_4.addWidget(self.RadioButton_5)
        self.RadioButton_6 = RadioButton(parent=self.widget)
        self.RadioButton_6.setObjectName("RadioButton_6")
        self.horizontalLayout_4.addWidget(self.RadioButton_6)

        self.methodgroup = QButtonGroup(parent=self.widget)  # group
        self.methodgroup.addButton(self.RadioButton_5)
        self.methodgroup.addButton(self.RadioButton_6)

        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.checkBox = CheckBox(parent=self.widget)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.pushButton = PrimaryPushButton(parent=self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.pushButton_2 = HyperlinkButton(parent=self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "192.168.200.2"))

        self.label_3.setText(_translate("Form", "url"))
        self.BodyLabel.setText(_translate("Form", "内网ip"))
        self.PushButton.setText(_translate("Form", "获取本机ip"))
        self.RadioButton_1.setText(_translate("Form", "移动"))
        self.RadioButton_2.setText(_translate("Form", "联通"))
        self.RadioButton_3.setText(_translate("Form", "电信"))
        self.RadioButton_5.setText(_translate("Form", "电脑端"))
        self.RadioButton_6.setText(_translate("Form", "移动端"))

        self.label_5.setText(_translate("Form", "用户名"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "统一认证号"))
        self.label_6.setText(_translate("Form", "密码"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", ""))
        self.checkBox.setText(_translate("Form", "记住本次选择"))
        self.pushButton.setText(_translate("Form", "登录"))
        self.pushButton_2.setText(_translate("Form", "自服务"))


from qfluentwidgets import BodyLabel, CheckBox, HyperlinkButton, LineEdit, PrimaryPushButton, PushButton, RadioButton

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
